# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: C Siva Prakash Reddy
title: Blockchain Developer
email: reddycsivaprakash5@gmail.com
website: https://github.com/Ad-h0c

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Adh0c__
github_username:  Ad-h0c
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: siva-prakash-reddy-c-7b63ab229
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Mypic.jpg
about_content: | # this will include new lines to allow paragraphs
  A logical and responsible person with a strong foundation in blockchain development. Proficient in Solidity, javascript, and familiar with the hardhat and truffle frameworks. In his learning career, he developed KYC application using solidity, p2p lending, and swap applications. He has hands-on experience integrating various wallets into applications, bridges, and oracles. He is also familiar with basic cryptographic algorithms. Looking to start a career as an entry-level blockchain developer.

  I am most skilled in: <mark>Solidity</mark> <mark>Javascript</mark> and <mark>Ethereum</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: P2P Lending And Borrowing
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Ad-h0c/p2plendingandborrowing
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning DAPP development and it has since grown into a fully fledged app. I have learned many skills creating this project including solidity, web3js, wallet integration, bootstrap etc.
      - layout: top-middle
        title: Pharma-network
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Ad-h0c/Pharma_network
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is my final blockchain captsone project I made using the hyperledger fabric and nodejs to solve the drug drug counterfeiting problem.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IIIT Bangalore
        caption: 2021 - 2022
        sub_title: Advanced Blockchain certification.
        quote: >
          The International Institute of Information Technology, Bangalore is a research university in Bangalore, India. The institute is a registered not-for-profit society funded jointly by the Government of Karnataka and the IT industry under a public-private partnership model.
        description: | # this will include new lines to allow paragraphs
          During my time at IIT Bangalore I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as a student and learnt a lot about a healthy work life balance.

          I spent a lot of my free time to learning other suitable skills needed for blockchain development.
      - layout: left
        title: Kristu Jayanti College
        caption: 2018 - 2021
        sub_title: Bachelor Of Computer Science.
        quote: >
          Kristu Jayanti College, founded in the year 1999, managed by "Bodhi Niketan Trust", formed by the members of St. Joseph Province of the Carmelites of Mary Immaculate. The college is affiliated to Bengaluru North University. The college is recognized by UGC under the category 2 & 12. 
        description: | # this will include new lines to allow paragraphs
          During my time at Kristu Jayanti College I learnt most of my key skills related to data science and analytics including the machine learning basics. 

          I spent my free time learning front end development and writing new articles.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Novel reading.
      - Gaming
      - Writing
      - Music

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
